### ISSUE TITLE
数据集标签格式

### ISSUE THREAD

**Issue by liuzhan123456** [lx-cly/YOLOv7_OBB#21]
您好，请问一下您数据集标签格式是五点法，还是4点坐标表示法，我用4点坐标表示法进行训练时，提示没有找到标签。
184.0 350.0 944.0 185.0 981.0 355.0 221.0 521.0 1 0这是我其中一个标签
部分报错
train: WARNING: Ignoring corrupted image and/or label data/ship-hrsc/train/images/100001680.jpg: The DType <class 'numpy._IntegerAbstractDType'> could not be promoted by <class 'numpy.dtypes.StrDType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy._IntegerAbstractDType'>, <class 'numpy.dtypes.StrDType'>)
train: Scanning 'data/ship-hrsc/train/labelTxt' images and labels... 617 found, 0 missing, 0 empty, 617 corrupted: 100%|█| 617/617
train: New cache created: data/ship-hrsc/train/labelTxt.cache
Traceback (most recent call last):
  File "/T2021069/YOLOv7cfg/train.py", line 618, in <module>
    train(hyp, opt, device, tb_writer)
  File "/T2021069/YOLOv7cfg/train.py", line 247, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt, names,
  File "/T2021069/YOLOv7cfg/utils/datasets.py", line 70, in create_dataloader
    dataset = LoadImagesAndLabels(path, names, imgsz, batch_size,
  File "/T2021069/YOLOv7cfg/utils/datasets.py", line 409, in __init__
    labels, shapes, self.segments = zip(*cache.values())
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by lx-cly** [comment]
Yolov7-OBB labels require 10 columns, which same as DOTA Dataset.也就是4点坐标+类别+难易程度。
`ValueError: not enough values to unpack (expected 3, got 0)` 就是你的cache文件中，没有一个有效标签。

**Comment by liuzhan123456** [comment]
好的，谢谢大哥，但看我数据集也没问题，在另一个yolov7代码也跑通了，想请问一下大哥，我该从哪方面下手排查问题

**Comment by lx-cly** [comment]
可以考虑下面的方法排查：
1. 删除cache文件，然后打断点到utils->datasets.py->cache_labels(函数)；
2. 函数中找到try语句那里，一行一行运行，看看是为什么跳到except中。

**Comment by HeiXiaoPi** [comment]
你好，我也遇到了相关的问题，解决了好几天，可否加个QQ一块研究，QQ：3317999280

**Comment by hecheng000** [comment]
> 3317999280

加你了 可以讨论一下

**Comment by zzbbzz626** [comment]
> 好的，谢谢大哥，但看我数据集也没问题，在另一个yolov7代码也跑通了，想请问一下大哥，我该从哪方面下手排查问题

请问你解决这个问题了吗？
