### ISSUE TITLE
Label visualization problems in test.py

### ISSUE THREAD

**Issue by jsago** [lx-cly/YOLOv7_OBB#3]
I want to know whether the code of test.py has not been modified,The proportion of the gt box in the visualization image becomes thinner，It's strange, but it's not like this in detect.py,and labels in the .txt format are only horizontal boxes, and only four coordinate parameters are included
![image](https://user-images.githubusercontent.com/24204254/204704276-1b71a61c-253b-444b-b056-67c5b965384e.png)
![image](https://user-images.githubusercontent.com/24204254/204704328-fab1eeee-c645-40a0-a14b-ceee0e392a69.png)
![image](https://user-images.githubusercontent.com/24204254/204704381-1677df43-5f05-41eb-855f-f444ec271d74.png)
![image](https://user-images.githubusercontent.com/24204254/204704633-75f44ce1-1c59-4ec4-a3f4-dd58e696e482.png)

**Comment by lx-cly** [comment]
when creating val_dataloader,the sign of `rect` is opened. the `targets` normalized to pixel  format is wrong. Now,`rect=False`,the gt box in visualization is correct.And in detect.py, I just save hbb pred results in the .txt format and save poly pred results in the .json format.If you want to get obb results, please save the json format.

**Comment by jsago** [comment]
> when creating val_dataloader,the sign of `rect` is opened. the `targets` normalized to pixel format is wrong. Now,`rect=False`,the gt box in visualization is correct.And in detect.py, I just save hbb pred results in the .txt format and save poly pred results in the .json format.If you want to get obb results, please save the json format.

Thank you very much for removing my doubts. I have another question. I hope I can get your answer. When I set task to speed or study in test.py, an error is reported:
Traceback (most recent call last):
  File "D:/Scientific_Research/YOLOv7_OBB_KLD/my_test.py", line 404, in <module>
    plots=False, v5_metric=opt.v5_metric)
  File "D:/Scientific_Research/YOLOv7_OBB_KLD/my_test.py", line 60, in test
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "D:\Scientific_Research\YOLOv7_OBB_KLD\models\experimental.py", line 252, in attempt_load
    ckpt = torch.load(w, map_location=map_location)  # load
  File "D:\Software Area\Anaconda\envs\Pytorch\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Software Area\Anaconda\envs\Pytorch\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Software Area\Anaconda\envs\Pytorch\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: '.'

**Comment by lx-cly** [comment]
> > when creating val_dataloader,the sign of `rect` is opened. the `targets` normalized to pixel format is wrong. Now,`rect=False`,the gt box in visualization is correct.And in detect.py, I just save hbb pred results in the .txt format and save poly pred results in the .json format.If you want to get obb results, please save the json format.
> 
> Thank you very much for removing my doubts. I have another question. I hope I can get your answer. When I set task to speed or study in test.py, an error is reported: Traceback (most recent call last): File "D:/Scientific_Research/YOLOv7_OBB_KLD/my_test.py", line 404, in plots=False, v5_metric=opt.v5_metric) File "D:/Scientific_Research/YOLOv7_OBB_KLD/my_test.py", line 60, in test model = attempt_load(weights, map_location=device) # load FP32 model File "D:\Scientific_Research\YOLOv7_OBB_KLD\models\experimental.py", line 252, in attempt_load ckpt = torch.load(w, map_location=map_location) # load File "D:\Software Area\Anaconda\envs\Pytorch\lib\site-packages\torch\serialization.py", line 579, in load with _open_file_like(f, 'rb') as opened_file: File "D:\Software Area\Anaconda\envs\Pytorch\lib\site-packages\torch\serialization.py", line 230, in _open_file_like return _open_file(name_or_buffer, mode) File "D:\Software Area\Anaconda\envs\Pytorch\lib\site-packages\torch\serialization.py", line 211, in **init** super(_open_file, self).**init**(open(name, mode)) PermissionError: [Errno 13] Permission denied: '.'

when you set task to speed or study in test.py，parser.add_argument('--weights'...) default=['{your_weigthts}'].
`elif opt.task == 'speed':  # speed benchmarks
    **for w in opt.weights**:`
